from typing import Protocol
from Models.alerte import AlerteDTO


class IAlerteRepository(Protocol):
    def get_all(self) -> list[AlerteDTO]: ...
    def get_by_id(self, id_alerte: int) -> AlerteDTO | None: ...
    def create(self, alerte: AlerteDTO) -> bool: ...
    def update(self, alerte: AlerteDTO) -> bool: ...
    def delete(self, id_alerte: int) -> bool: ...