from typing import Protocol
from Models.commande import CommandeDTO


class ICommandeRepository(Protocol):
    def get_all(self) -> list[CommandeDTO]: ...
    def get_by_id(self, id_commande: int) -> CommandeDTO | None: ...
    def create(self, commande: CommandeDTO) -> bool: ...
    def update(self, commande: CommandeDTO) -> bool: ...
    def delete(self, id_commande: int) -> bool: ...