from typing import Protocol
from Models.emprunt import EmpruntDTO


class IEmpruntRepository(Protocol):
    def get_all(self) -> list[EmpruntDTO]: ...
    def get_by_id(self, id_emprunt: int) -> EmpruntDTO | None: ...
    def find_emprunt_actif(
        self,
        id_etudiant: int,
        id_materiel: int
    ) -> EmpruntDTO | None: ...
    def create(self, emprunt: EmpruntDTO) -> bool: ...
    def update(self, emprunt: EmpruntDTO) -> bool: ...
    def delete(self, id_emprunt: int) -> bool: ...