from typing import Protocol
from Models.etudiant import EtudiantDTO


class IEtudiantRepository(Protocol):
    def get_all(self) -> list[EtudiantDTO]: ...
    def get_by_id(self, id_etudiant: int) -> EtudiantDTO | None: ...
    def find_by_email(self, email: str) -> EtudiantDTO | None: ...
    def create(self, etudiant: EtudiantDTO) -> bool: ...
    def update(self, etudiant: EtudiantDTO) -> bool: ...
    def delete(self, id_etudiant: int) -> bool: ...