from typing import Protocol
from Models.fournisseur import FournisseurDTO


class IFournisseurRepository(Protocol):
    def get_all(self) -> list[FournisseurDTO]: ...
    def get_by_id(self, id_fournisseur: int) -> FournisseurDTO | None: ...
    def create(self, fournisseur: FournisseurDTO) -> bool: ...
    def update(self, fournisseur: FournisseurDTO) -> bool: ...
    def delete(self, id_fournisseur: int) -> bool: ...