from typing import Protocol
from Models.gestionnaire import GestionnaireDTO


class IGestionnaireRepository(Protocol):
    def get_all(self) -> list[GestionnaireDTO]: ...
    def get_by_id(self, id_gestionnaire: int) -> GestionnaireDTO | None: ...
    def find_by_email(self, email: str) -> GestionnaireDTO | None: ...
    def create(self, gestionnaire: GestionnaireDTO) -> bool: ...
    def update(self, gestionnaire: GestionnaireDTO) -> bool: ...
    def delete(self, id_gestionnaire: int) -> bool: ...