from typing import Protocol
from Models.ligne_commande import LigneCommandeDTO


class ILigneCommandeRepository(Protocol):
    def get_all(self) -> list[LigneCommandeDTO]: ...
    def get_by_id(self, id_ligne: int) -> LigneCommandeDTO | None: ...
    def find_by_commande(self, id_commande: int) -> list[LigneCommandeDTO]: ...
    def create(self, ligne: LigneCommandeDTO) -> bool: ...
    def update(self, ligne: LigneCommandeDTO) -> bool: ...
    def delete(self, id_ligne: int) -> bool: ...