from typing import Protocol
from Models.machine import MachineDTO


class IMachineRepository(Protocol):
    def get_all(self) -> list[MachineDTO]: ...
    def get_by_id(self, id_machine: int) -> MachineDTO | None: ...
    def find_disponibles(self) -> list[MachineDTO]: ...
    def find_hors_service(self) -> list[MachineDTO]: ...
    def find_by_type(self, type_machine: str) -> list[MachineDTO]: ...
    def create(self, machine: MachineDTO) -> bool: ...
    def update(self, machine: MachineDTO) -> bool: ...
    def delete(self, id_machine: int) -> bool: ...