from typing import Protocol
from Models.machine import MachineDTO


class IMachineRepository(Protocol):
    def get_all(self) -> list[MachineDTO]: ...
    def get_by_id(self, id_machine: int) -> MachineDTO | None: ...
    def create(self, machine: MachineDTO) -> bool: ...
    def update(self, machine: MachineDTO) -> bool: ...
    def delete(self, id_machine: int) -> bool: ...