from typing import Protocol
from Models.materiel import MaterielDTO


class IMaterielRepository(Protocol):
    def get_all(self) -> list[MaterielDTO]: ...
    def get_by_id(self, id_materiel: int) -> MaterielDTO | None: ...
    def get_stock_faible(self) -> list[MaterielDTO]: ...
    def create(self, materiel: MaterielDTO) -> bool: ...
    def update(self, materiel: MaterielDTO) -> bool: ...
    def delete(self, id_materiel: int) -> bool: ...