from typing import Protocol
from Models.mouvement_stock import MouvementStockDTO


class IMouvementStockRepository(Protocol):
    def get_all(self) -> list[MouvementStockDTO]: ...
    def get_by_id(self, id_mouvement: int) -> MouvementStockDTO | None: ...
    def get_by_materiel(self, id_materiel: int) -> list[MouvementStockDTO]: ...
    def find_by_type(self, type_mouvement: str) -> list[MouvementStockDTO]: ...
    def find_by_periode(self, date_debut: str, date_fin: str) -> list[MouvementStockDTO]: ...
    def create(self, mouvement: MouvementStockDTO) -> bool: ...
    def update(self, mouvement: MouvementStockDTO) -> bool: ...
    def delete(self, id_mouvement: int) -> bool: ...