from typing import Protocol
from Models.reservation import ReservationDTO


class IReservationRepository(Protocol):
    def get_all(self) -> list[ReservationDTO]: ...
    def get_by_id(self, id_reservation: int) -> ReservationDTO | None: ...
    def find_by_machine_and_date(
        self,
        id_machine: int,
        date_reservation: str
    ) -> list[ReservationDTO]: ...
    def create(self, reservation: ReservationDTO) -> bool: ...
    def update(self, reservation: ReservationDTO) -> bool: ...
    def delete(self, id_reservation: int) -> bool: ...