from .home_view import MainScreen
from .login_view import LoginView
from .dashboard_view import DashboardView
from .stock_view import StockView
from .emprunt_view import EmpruntView
from .alerte_view import AlerteView
from .machine_view import MachineView
from .reservation_view import ReservationView
from .fournisseur_view import FournisseurView
from .commande_view import CommandeView
from .historique_view import HistoriqueView